name: notejam python

on: [push]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 2.7.16
      uses: actions/setup-python@v1
      with:
        python-version: 2.7.16
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r /django/requirements.txt
    - name: create db schema
      run: |
        cd /django/notejam/
        ./manage.py syncdb
        ./manage.py migrate
    - name: launch
      run: |
        cd /django/notejam/
        ./manage.py runserver
    - name: Test
      run: |
        cd /django/notejam/
        ./manage.py test
